
services:
  waf:
    container_name: modsecurity
    build:
      context: .
      dockerfile: modsec/Dockerfile
    restart: always
    depends_on:
      backend:
        condition: service_healthy
      vault:
        condition: service_healthy
    volumes:
      - ./volumes/nginx_logs:/var/log/nginx
      - ./volumes/tls:/etc/ssl/local
    ports:
      - "8080:80"
      - "4004:443"
    networks:
      - transcendence
    healthcheck:
      test: ["CMD-SHELL", "curl -fk https://localhost/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  vault:
    container_name: vault
    build:
      context: ./vault
      dockerfile: Dockerfile
    environment:
      VAULT_DEV_ROOT_TOKEN: myroot
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_API_ADDR: http://127.0.0.1:8200
    volumes:
      - ./volumes/backend_secrets:/run/secrets
      - ./volumes/tls:/out
    networks:
      - transcendence
    healthcheck:
      test: ["CMD-SHELL", "test -s /run/secrets/app.env && grep -q '^JWT_SECRET=' /run/secrets/app.env test -s /out/fullchain.pem -a -s /out/privkey.pem"]
      interval: 5s
      timeout: 2s
      retries: 30
    restart: always

  backend:
    container_name: backend
    depends_on:
      vault:
        condition: service_healthy
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./volumes/backend_data:/app/data
      - ./volumes/backend_secrets:/run/secrets
      - ./volumes/backend_avatars:/app/public/avatars
      - ./volumes/backend_logs:/app/logUtils/logs
    expose:
    - "3000" # Expose backend API port
    networks:
      - transcendence
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_API_ADDR: http://vault:8200
    healthcheck:
      # bookworm-slim: install curl in the Dockerfile (see below)
      test: ["CMD-SHELL", "curl http://localhost:3000/status >/dev/null|| exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 20s
    restart: always


networks:
  transcendence:


